<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 1" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="E:\python\python_workplace\MachineLearning\src\SVM\SVM3.py" status="error" test="SVM3" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Administrator\.p2\pool\plugins\org.python.pydev_5.7.0.201704111357\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "E:/python/python_workplace/MachineLearning/src/SVM\SVM3.py", line 6
    '''
     ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc4 in position 16: invalid continuation byte
ERROR: Module: SVM3 could not be imported (file: E:\python\python_workplace\MachineLearning\src\SVM\SVM3.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="MachineLearning SVM3.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
